#ifndef BEEBJIT_ASM_INTURBO_DEFS_H
#define BEEBJIT_ASM_INTURBO_DEFS_H

#define K_INTURBO_OPCODES                  0x40000000
#define K_INTURBO_OPCODES_SHIFT            8

#endif /* BEEBJIT_ASM_INTURBO_DEFS_H */

