#ifndef BEEBJIT_ASM_TABLES_DEFS_H
#define BEEBJIT_ASM_TABLES_DEFS_H

#include "asm_defs_host.h"

#define K_ASM_TABLE_6502_FLAGS_TO_X64           K_ASM_TABLE_ADDR
#define K_ASM_TABLE_6502_FLAGS_TO_MASK          (K_ASM_TABLE_ADDR + 0x100)
#define K_ASM_TABLE_X64_FLAGS_TO_6502           (K_ASM_TABLE_ADDR + 0x200)
#define K_ASM_TABLE_PAGE_WRAP_CYCLE_INV         (K_ASM_TABLE_ADDR + 0x300)
#define K_ASM_TABLE_OF_TO_6502                  (K_ASM_TABLE_ADDR + 0x500)
#define K_ASM_TABLE_6502_FLAGS_TO_X64_OFFSET    0
#define K_ASM_TABLE_6502_FLAGS_TO_MASK_OFFSET   0x100
#define K_ASM_TABLE_X64_FLAGS_TO_6502_OFFSET    0x200
#define K_ASM_TABLE_PAGE_WRAP_CYCLE_INV_OFFSET  0x300
#define K_ASM_TABLE_OF_TO_6502_OFFSET           0x500

#endif /* BEEBJIT_ASM_TABLES_DEFS_H */
